import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

Color whiteColor = const Color(0xffFFFFFF);
Color blackColor = const Color(0xff14193F);
Color greyColor = const Color(0xffC9C6C6);
Color greyItemColor = const Color(0xffD2D2D2);
Color greyItemTextColor = const Color(0xff9D9D9D);
Color lightBackgroundColor = const Color(0xffF5F5F5);
Color greenColor =   Color.fromARGB(255, 35, 83, 108);
Color greenTxtColor = const Color(0xff394929);
Color greenTxt2Color = Color.fromARGB(255, 26, 75, 110);
Color rectangleColor = Color.fromARGB(255, 35, 60, 109);
Color weatherColor = Color.fromARGB(255, 35, 68, 128);
Color piechartColor1 = const Color(0xffD3D3D3);
Color piechartColor2 = Color.fromARGB(255, 35, 68, 128);
TextStyle blackTextStyle = GoogleFonts.poppins(color: blackColor);
TextStyle greenTextColor = GoogleFonts.poppins(color: greenTxtColor);
TextStyle greenTextYoungColor = GoogleFonts.poppins(color: greenTxt2Color);
TextStyle greyTextYoungColor = GoogleFonts.poppins(color: greyItemTextColor);
TextStyle whiteTextStyle = GoogleFonts.poppins(color: whiteColor);
TextStyle greyTextStyle = GoogleFonts.poppins(color: greyColor);
TextStyle weatherTextStyle = GoogleFonts.poppins(color: weatherColor);

FontWeight light = FontWeight.w300;
FontWeight regular = FontWeight.w400;
FontWeight medium = FontWeight.w500;
FontWeight semiBold = FontWeight.w600;
FontWeight bold = FontWeight.w700;
FontWeight extraBold = FontWeight.w800;
FontWeight black = FontWeight.w900;
